# Generated by Django 5.2.17 on 2026-08-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0018_teamworkflowsconfig_ses_tenant_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="hogflow",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[("broadcast", "Broadcast")],
                max_length=40,
                null=True,
            ),
        ),
    ]
